### PR TITLE
Refactored contributions to Prepare For V2

### PR DESCRIPTION
**Pull request by caseycrogers**
This does some refactoring/trimming of @martijn00 contributions.

The biggest changes:
1. `GutterType` is removed-it complicated the API without a clear external benefit
2. The alternate constructors were retained, but I made them factories that are thin shims on top of the alternate classes. This loses `const`, but it's the best way I could find for now that allows for alternate constructors without complicating the API significantly. My gut check is that most users will prefer to use the non-alternate-constructor classes so I wanted to disrupt the package as little as possible in keeping this in
3. I removed `AdaptiveGutter`. I still really don't get why it would be useful. From what I can tell, it fluidly transitions between different gutter scalings when the screen size changes (ie unfolding a folding phone). This doesn't make any sense to me because gutter scalings are for different sizes of gutter WITHIN a screen size, not across screen sizes. Changing across sizes is already handled by the breakpoints and material spacing logic. If you want that to fluidly animate, then wouldn't it make sense to handle the animation in the underlying material spacing logic?
Ex: if I'm on a small screen with gutter small, my size is `16*.5=8`. If I unfolded my phone and thus moved to a medium breakpoint, then adaptive gutter would switch to gutter medium and a material spacing of 24: `24*1=24`. Why are we changing the gutter type when the change in breakpoint was already changing the spacing?
4. I removed the manual size on `Gutter` and brought back `Gap`. The whole point of a gutter widget is it handles sizing for you. I think it's better to have custom sizes in a separate widget, especially because that means the separate widget can mirror the more popular Gap package.
5. renamed `GutterMargin` back to `Margin`.
6. I moved all the default spacings and scalings into `GutterConfiguration` and made them customizable.
7. Removed `GutterPadding`, as previously discussed I think it doesn't add enough value relative `Padding` with the gutter build extensions.
8. Removed `GutterSize` as it was polluting the public API
9. Made all expected outcomes in tests hardcoded numbers rather than calculated by flutter gutter itself

Particularly on `AdaptiveGutter` but on any of the changes here, feel free to file an issue explaining why you want it/what it does and we can consider bringing it back in

### CODE REVIEW

**Comment by caseycrogers** [comment]
My oonga boonga brain could not figure out how to trigger the automated deploys so I just manually published right now. v2.0.0 is out!

**Comment by martijn00** [comment]
1. Sure
2. I understand that you prefer another way, i'll try and find a way to make it const again and make a PR
3. Sure, i can also just add this to my own code base, it's just a little helper
4. I'm sad that this option is gone hehe. I really wanted manual sizing for my apps for this lib. I guess i can use Gap now but i just know that other devs won't discover Gap so easily. I'll see if i can find a way.
5. Sure
6. I like this one, nice!
7. Yes
8. Yes
9. Good!

On the automatic release: You just need to create a GIT tag with `v2.0.x` or something and push that tag and it'll do it all for you.

**Comment by caseycrogers** [comment]
I've got a way to make them const that isn't too painful, will work on it today and cc you on the PR if you're curious/have any input.

**Comment by martijn00** [comment]
Sure! Tag me in the pr and I'll review!

**Pull request merged**
