### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by martijn00**
## Connection with issue(s)

Close #10 

## Solution description

This adds a whole bunch of tests. Some of which you might want to fix.

## To Do

- [ ] Check the original issue to confirm it is fully satisfied
- [ ] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behavior
- [ ] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Comment by martijn00** [comment]
@caseycrogers I've added some stuff on top of your PR. There are some tests in here that fail. You might just want to disable those for now, or if you have an idea to fix them?

**Comment by caseycrogers** [comment]
Cool yeah I was thinking of adding tests for each axis but had been too lazy, glad you added it!

**Comment by martijn00** [comment]
Thanks! Will you fix the tests that don't run?

**Comment by caseycrogers** [comment]
Yep will take a look at it.

**Pull request merged**
